wandb_version: 1

augment:
  value: true
batch_norm:
  value: false
conv_activation:
  value: GELU
dropout:
  value: 0.3
epochs:
  value: 20
kernel_size:
  value: 7
learning_rate:
  value: 0.0001
num_filters:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
