wandb_version: 1

augment:
  value: true
batch_norm:
  value: true
conv_activation:
  value: SiLU
dropout:
  value: 0.2
epochs:
  value: 20
kernel_size:
  value: 5
learning_rate:
  value: 1.0e-05
num_filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 256
