wandb_version: 1

augment:
  value: true
batch_norm:
  value: false
conv_activation:
  value: Mish
dropout:
  value: 0.2
epochs:
  value: 20
kernel_size:
  value: 5
learning_rate:
  value: 0.001
num_filters:
  value:
  - 64
  - 64
  - 64
  - 64
  - 64
