wandb_version: 1

augment:
  value: true
batch_norm:
  value: true
conv_activation:
  value: ReLU
dropout:
  value: 0
epochs:
  value: 20
kernel_size:
  value: 3
learning_rate:
  value: 1.0e-05
num_filters:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
