wandb_version: 1

augment:
  value: true
batch_norm:
  value: true
conv_activation:
  value: SiLU
dropout:
  value: 0
epochs:
  value: 20
kernel_size:
  value: 7
learning_rate:
  value: 0.0001
num_filters:
  value:
  - 32
  - 64
  - 128
  - 64
  - 32
